include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_print: false  # 允许使用print
    - prefer_const_constructors: true
    - prefer_const_literals_to_create_immutables: true
    - prefer_final_fields: true
    - prefer_final_locals: true
    - avoid_unnecessary_containers: true
    - sized_box_for_whitespace: true
    - use_key_in_widget_constructors: true
    - prefer_single_quotes: true
    - sort_constructors_first: true
    - avoid_redundant_argument_values: false
